import { env } from '$env/dynamic/private';
import type { Courier } from '@prisma/client';

/**
 * inobags.com WooCommerce REST client.
 *
 * Order documents (НАП "Документ за поръчка") are generated by the
 * Bulgarisation for WooCommerce plugin and stored as WP attachments; the
 * attachment id sits in order meta `woo_bg_order_document`. Waybill numbers
 * come from the same plugin's label meta.
 */

export type WooOrder = {
	id: number;
	number: string;
	status: string;
	date_created_gmt: string;
	total: string;
	payment_method: string;
	payment_method_title: string;
	billing: { first_name?: string; last_name?: string; company?: string };
	meta_data: Array<{ key: string; value: unknown }>;
};

export type ParsedWooOrder = {
	externalId: number;
	orderNumber: string;
	orderDate: Date;
	status: string;
	totalCents: number;
	paymentMethod: string;
	paymentMethodTitle: string | null;
	customerName: string;
	courier: Courier | null;
	waybillNumber: string | null;
	documentNumber: string | null;
	documentAttachmentId: number | null;
	raw: WooOrder;
};

export function wooConfigured(): boolean {
	return Boolean(env.WOOCOMMERCE_URL && env.WOOCOMMERCE_CONSUMER_KEY && env.WOOCOMMERCE_CONSUMER_SECRET);
}

function baseUrl() {
	return (env.WOOCOMMERCE_URL ?? '').replace(/\/+$/, '');
}

function authHeader() {
	const token = Buffer.from(`${env.WOOCOMMERCE_CONSUMER_KEY}:${env.WOOCOMMERCE_CONSUMER_SECRET}`).toString('base64');
	return { Authorization: `Basic ${token}` };
}

function meta(order: WooOrder, key: string): unknown {
	return order.meta_data.find((m) => m.key === key)?.value;
}

export function parseWooOrder(order: WooOrder): ParsedWooOrder {
	const econtLabel = meta(order, 'woo_bg_econt_label') as { label?: { shipmentNumber?: string } } | undefined;
	const speedyLabel = meta(order, 'woo_bg_speedy_label') as { id?: string | number } | undefined;
	const econtWaybill = econtLabel?.label?.shipmentNumber;
	// Since 08.2026 Speedy labels come from a different plugin that stores `_speedy_awb`.
	const speedyWaybill = speedyLabel?.id ?? (meta(order, '_speedy_awb') as string | undefined);

	const attachment = Number(meta(order, 'woo_bg_order_document'));
	const docNumber = meta(order, 'woo_bg_order_number');
	const name = [order.billing.first_name, order.billing.last_name].filter(Boolean).join(' ').trim();

	return {
		externalId: order.id,
		orderNumber: order.number,
		orderDate: new Date(order.date_created_gmt + 'Z'),
		status: order.status,
		totalCents: Math.round(parseFloat(order.total) * 100),
		paymentMethod: order.payment_method,
		paymentMethodTitle: order.payment_method_title || null,
		customerName: name || order.billing.company || '—',
		courier: econtWaybill ? 'econt' : speedyWaybill ? 'speedy' : null,
		waybillNumber: econtWaybill ? String(econtWaybill) : speedyWaybill ? String(speedyWaybill) : null,
		documentNumber: docNumber ? String(docNumber) : null,
		documentAttachmentId: Number.isFinite(attachment) && attachment > 0 ? attachment : null,
		raw: order
	};
}

/** Orders created in [after, before), all statuses. */
export async function fetchWooOrders(after: Date, before: Date): Promise<ParsedWooOrder[]> {
	const out: ParsedWooOrder[] = [];
	for (let page = 1; ; page++) {
		const qs = new URLSearchParams({
			after: after.toISOString(),
			before: before.toISOString(),
			per_page: '100',
			page: String(page),
			orderby: 'id',
			order: 'asc'
		});
		const res = await fetch(`${baseUrl()}/wp-json/wc/v3/orders?${qs}`, { headers: authHeader() });
		if (!res.ok) {
			throw new Error(`WooCommerce: HTTP ${res.status} ${(await res.text()).slice(0, 200)}`);
		}
		const batch = (await res.json()) as WooOrder[];
		out.push(...batch.map(parseWooOrder));
		const totalPages = Number(res.headers.get('x-wp-totalpages') ?? '1');
		if (page >= totalPages || batch.length === 0) break;
	}
	return out;
}

/** Downloads the order document PDF behind a WP attachment id. */
export async function fetchWooOrderDocument(
	attachmentId: number
): Promise<{ filename: string; blob: Uint8Array<ArrayBuffer> } | null> {
	const mediaRes = await fetch(`${baseUrl()}/wp-json/wp/v2/media/${attachmentId}`);
	if (!mediaRes.ok) return null;
	const media = (await mediaRes.json()) as { source_url?: string; mime_type?: string };
	if (!media.source_url || media.mime_type !== 'application/pdf') return null;

	const fileRes = await fetch(media.source_url);
	if (!fileRes.ok) return null;
	return {
		filename: media.source_url.split('/').pop() ?? `${attachmentId}.pdf`,
		blob: new Uint8Array(await fileRes.arrayBuffer())
	};
}
